x-build: &build                       # ← reusable block
  context: .
  dockerfile: docker/Dockerfile      # path inside the repo

services:
  mini-ca-init:
    image: minica:latest             # still tags the image so it can cache
    build: *build                    # ← add this line
    command: ["init", "--force"]
    user: root
    volumes:
      - mini-data:/data

  mini-ca:
    image: minica:latest
    build: *build                    # ← add this line
    command: ["watch", "--file", "/data/DOMAINS"]
    volumes:
      - mini-data:/data
    depends_on:
      mini-ca-init:
        condition: service_completed_successfully
    restart: unless-stopped          # long‑running service
  mini-ca-cli:
      image: minica:latest
      profiles: [ "cli" ] # keeps it from starting automatically
      volumes:
        - mini-data:/data
      entrypoint: [ "mini_ca.py" ]

volumes:
  mini-data:
