
volumes:
  mini-data:

x-build: &mini-build
  context: .              # <-- matches the Dockerfile directory
  dockerfile: docker/Dockerfile

services:
# ----------------------------------------------------------------------
# 1) one‑shot initialiser (fixes volume ownership + creates root CA)
# ----------------------------------------------------------------------
  mini-ca-init:
    image: minica:latest
    build: *mini-build
    user: root
    entrypoint: [ "/bin/sh", "-c" ]      #  <<< FIXED
    command: |
      echo '[init] fixing perms…'        &&
      chown -R 1001:1001 /data 2>/dev/null || true &&
      echo '[init] generating / refreshing root CA…' &&
      su myca -s /bin/sh -c 'mini_ca.py init --force'
    volumes:
      - mini-data:/data
    restart: "no"

# ----------------------------------------------------------------------
# 2) Long‑running CA service (optional watcher)
# ----------------------------------------------------------------------
  mini-ca:
    image: minica:latest
    build: *mini-build
    user: 1001:1001
    entrypoint: [ "mini_ca.py" ]   # keep the Typer CLI
    # uncomment to run in watch mode all the time
    # command: [ "watch", "--file", "/data/DOMAINS" ]
    depends_on:
      mini-ca-init:
        condition: service_completed_successfully
    volumes:
      - mini-data:/data
