################################################################
# drop‑in snippet – adjust indent & add to your own compose
################################################################
services:
  minica:
    image: minica:latest          # make sure you built the image first
    # build:
    #   context: ./mini-ca
    #   dockerfile: docker/Dockerfile
    volumes:
      - mini-data:/data           # or an absolute host path
    # environment:
    #   MYCA_ROOT: /data/rootCA
    #   MYCA_CERTS: /data/certificates
    #   UID: "1001"               # build‑arg; document here
    command: [ "--help" ]         # change to `watch` / `init` / `issue …`

volumes:
  mini-data:
